### PR TITLE
Remove `cobjrun`  command

### PR DESCRIPTION
**Pull request by tsh-hashimoto**
Since `cobjrun` command has not been maintained for a while, I would like to remove it.

Main changes
* Remove `bin` directory, which contains `cobjrun` command.
* Update `Makefile.am` and `configure.ac` to exclude `bin` directory from build target.
  * When I ran `autoreconf`, the message `lib/Makefile.am:22: error: library used but 'RANLIB' is undefined` displayed.  So I added `AC_PROG_RANLIB` to `lib/Makefile.am`.

After making these changes, I ran `cobjrun` again (if `usr/lib/cobjrun` remained, remove it).
It could be confirmed that `cobjrun` is not available.

```
$ cobjrun
Command 'cobjrun' not found, did you mean:
  command 'cobcrun' from deb gnucobol3 (3.1.2-5)
  command 'cobcrun' from deb gnucobol4 (4.0~early~20200606-6)
Try: sudo apt install <deb name>
```

### CODE REVIEW

**Comment by yutaro-sakamoto** [comment]
As I discussed with you earlier, we have decided to keep cobjrun.

**Comment by tsh-hashimoto** [comment]
I understood, thanks.
But, as in [Issue#514](https://github.com/opensourcecobol/opensourcecobol4j/issues/514), `cobjrun` has a problem that options are not output correctly.
If we keep `cobjrun`, we have to fix this problem.

**Comment by yutaro-sakamoto** [comment]
The priority of fixing cobjrun is low.
We will resolve other issues first.

**Comment by tsh-hashimoto** [comment]
OK, thanks!

**Pull request closed without merging**
