### PR TITLE
Add devcontainer

### PR DESCRIPTION
**Pull request by yutaro-sakamoto**
This pull request introduces a variety of changes to the development environment setup, static analysis workflow, and code formatting for the OpenSource COBOL 4J project. The most important changes include setting up a new development container, updating the static analysis workflow to use `almalinux`, and switching from Google Java Format to Spotless for code formatting.

### Development Environment Setup:
* [`.devcontainer/Dockerfile`](diffhunk://#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6R1-R12): Added a new Dockerfile based on `almalinux:9` with necessary dependencies for building and testing the project.
* [`.devcontainer/boot.sh`](diffhunk://#diff-119075d89ac87a22250389b2630cec3460f779cf743d289e5658d3e548c47b17R1-R16): Added a script to build and install the project, and set up a pre-commit hook for formatting.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R1-R7): Added configuration for the development container to use the new Dockerfile and boot script.

### Static Analysis Workflow:
* [`.github/workflows/static-analysis.yml`](diffhunk://#diff-e9db86b6fd5f791eb849075b600b921e5e95b978e41f9d290c01027440076ec3R12-L13): Updated the workflow to use `almalinux:9` container and install dependencies using `dnf` instead of `apt-get`. [[1]](diffhunk://#diff-e9db86b6fd5f791eb849075b600b921e5e95b978e41f9d290c01027440076ec3R12-L13) [[2]](diffhunk://#diff-e9db86b6fd5f791eb849075b600b921e5e95b978e41f9d290c01027440076ec3L24-R37) [[3]](diffhunk://#diff-e9db86b6fd5f791eb849075b600b921e5e95b978e41f9d290c01027440076ec3L48-R52)

### Code Formatting:
* [`libcobj/app/build.gradle.kts`](diffhunk://#diff-6c03adcfe6eca0dada6741712494827ee4b347a697040251405115c2c5fda8fbR6-L7): Replaced Google Java Format with Spotless for code formatting because the behaviour of [the old formatter](https://github.com/sherter/google-java-format-gradle-plugin) is unstable. [[1]](diffhunk://#diff-6c03adcfe6eca0dada6741712494827ee4b347a697040251405115c2c5fda8fbR6-L7) [[2]](diffhunk://#diff-6c03adcfe6eca0dada6741712494827ee4b347a697040251405115c2c5fda8fbR62-R67)
* [`format`](diffhunk://#diff-e904c9ccfa425ff0b055d2c533462314d35a529b055e8abe41d49bb46d827427L2-R2): Updated the format script to use Spotless.
* [`check-format`](diffhunk://#diff-67d1ff9208316bd23d28f33879b999ca74f58d2a6734a8846d7f3c9d4beaf25cL2-R2): Updated the check-format script to use Spotless.

### Code Cleanup:
* [`cobj/codegen.c`](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L90-R90): Removed unused variable `extrefs` and commented out an unused struct member. [[1]](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L90-R90) [[2]](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L1419-L1422) [[3]](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L1509) [[4]](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L1581) [[5]](diffhunk://#diff-92e09701bd613a805e09be47306909e3e3abb869c44ad69ad4695ba84bb0c421L1590-L1595)
* [`cobj/cpp-check`](diffhunk://#diff-25298cc93dca4dd5c5350ac209f590c772a9d35e8043c94e5ceca1c245c071dcL8-R11): Added suppressions for unused struct members and other warnings in `cppcheck`.

### Format C files and Java files with new formatter in the Devcontainer
clang-format and a new formatter spotless formated all C files and Java files in the development environment.

### CODE REVIEW

**Comment by yutaro-sakamoto** [comment]
@tsh-hashimoto @kio-watanabe 
Please read CONTRIBUTING.md or CONTRIBUTING_JP.md and create a new development environment.
**This is the highest priority task related to opensource COBOL 4J.**

As explained in CONTRIBUTING.md, I suggest that we use Dev Containers of Visual Studio Code as a standard development environment.
If you success to create a new development environment and find no issue, please aprove reviews I requested.
Otherwise, please give me your questions and suggestions.

**Comment by tsh-hashimoto** [comment]
Just in case...

> 4. Clone the repository

Is it alright to clone the repository `yutaro-sakamoto:add-devcontainer`?
(It may a temporary concern.  Once your changes are merged, It will not to be necessary to worry about)

**Comment by yutaro-sakamoto** [comment]
@tsh-hashimoto 
Yes, you can clone `yutaro-sakamoto:add-devcontainer`.

Prepare an opensource COBOL 4J repository with the contents of the yutaro-sakamoto:add-devcontainer branch, either by git clone or git checkout.

**Comment by tsh-hashimoto** [comment]
Thanks.
It seemed to be able to set up the Docker environment.
スクリーンショット 2024-10-28 111051

I'll approve this PR.

**Review by tsh-hashimoto — APPROVED** [review]
I could create the environment.

**Comment by yutaro-sakamoto** [comment]
@kio-watanabe 
I have merged this pull request because @tsh-hashimoto verified that the new development environment worked.
Please try to create the new development environment on your machine.

**Pull request merged**
