### PR TITLE
Fix typos of cobj-idx cmd

### PR DESCRIPTION
**Pull request by royxue**
Hi, I'm new to this project, when I went through the README, I found there are some typos in cobj-idx cmd.
So I made some changes of it.
Hope it helps ;)

### CODE REVIEW

**Comment by yutaro-sakamoto** [comment]
Thank you so much!

**Comment by royxue** [comment]
@yutaro-sakamoto Thanks for your review! Glad that I could help.

My team are very interested in COBOL migration projects. As you are the main contributor of this opensourcecobol4j, I wonder if there is any opportunities that we could connect with you, and I can do an introduction of our team and ideas. If better we would like to hear about your opinions, and ask you more about how could we contribute to this project.

**Comment by royxue** [comment]
@yutaro-sakamoto My teammate Ali has also sent an email to your personal address, though it may have ended up in your spam folder. Our team, with background from Github Copilot and Carnegie Mellon University, are dedicated to dive deep into COBOL migration, would love to discuss with you in more detail.

**Comment by yutaro-sakamoto** [comment]
@royxue 
Thank you for contacting us.
My supervisor and I are discussing the matter you have contacted us about. We will get back to you by the end of next week and hope you will be able to wait a little longer.

**Comment by royxue** [comment]
@yutaro-sakamoto Thanks for your reply, and yes, we definitely can wait for the further feedback. Thanks a lot.

**Comment by yutaro-sakamoto** [comment]
@royxue 
My supervisor will reply to your email today regarding the matter you contacted us about. Please check your email.

**Comment by royxue** [comment]
@yutaro-sakamoto ありがとうございます！

**Pull request merged**
